# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sovereign.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sovereign.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsovereign.proto\x12\tsovereign\"?\n\x0cTradeRequest\x12\x0c\n\x04side\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x12\n\nexpected_e\x18\x03 \x01(\x01\"G\n\rTradeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x14\n\x0ctx_signature\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2M\n\x08\x45xecutor\x12\x41\n\x0c\x45xecuteTrade\x12\x17.sovereign.TradeRequest\x1a\x18.sovereign.TradeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sovereign_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRADEREQUEST']._serialized_start=30
  _globals['_TRADEREQUEST']._serialized_end=93
  _globals['_TRADERESPONSE']._serialized_start=95
  _globals['_TRADERESPONSE']._serialized_end=166
  _globals['_EXECUTOR']._serialized_start=168
  _globals['_EXECUTOR']._serialized_end=245
# @@protoc_insertion_point(module_scope)
